### PR TITLE
Add DateTime support

### PR DESCRIPTION
**Pull request by williambogaiv**
Could not add `DateTimeOffset`. See message below.

### CODE REVIEW

**Comment by jrusbatch** [comment]
:sparkles:

**Comment by jrusbatch** [comment]
Just kidding.

**Comment by williambogaiv** [comment]
Adding this so it doesn't get lost in the commit-messages:

> DateTimeOffset not added due to issues with Convert.
> See https://connect.microsoft.com/VisualStudio/feedback/details/1122089/convert-changetype-works-for-datetime-but-not-for-datetimeoffset

**Pull request merged**
