### PR TITLE
Revert "Add nuspec for NEST project"

### PR DESCRIPTION
**Pull request by khalidabuhakmeh**
Reverts ritterim/filter#35

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
@billbogaiv

**Comment by billbogaiv** [comment]
Yeah, should have tagged that PR as a
# wOrK iN pRoGrEsS.

**Comment by billbogaiv** [comment]
TIME COP RULZ!!!

**Comment by jrusbatch** [comment]
Ready for @ritterim/qa.

**Pull request merged**
